language: go
go:
  - "1.12"
install: skip
os:
  - linux
script: skip
env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0

jobs:
  include:
    - stage: test
      name: Run Tests
      install:
        - go mod download
        - go get -u github.com/mattn/goveralls
      script:
        - go test -v -covermode=count -coverprofile=coverage.out .
        - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN || true'
